import{a as S,S as $,i as d}from"./assets/vendor-CQi4fInE.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const q="55080821-ae3987ed548899e0d87a95a06",P="https://pixabay.com/api/";async function u(t,r){const s=new URLSearchParams({key:q,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:15});return(await S.get(`${P}?${s}`)).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=document.querySelector(".load-more"),B=new $(".gallery a",{captionsData:"alt",captionDelay:250});function h(t){const r=t.map(({webformatURL:s,largeImageURL:a,tags:e,likes:o,views:n,comments:b,downloads:w})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${a}">
        <img class="gallery-image" src="${s}" alt="${e}" />
      </a>
      <div class="info">
        <div class="info-item"><b>Likes</b><span>${o}</span></div>
        <div class="info-item"><b>Views</b><span>${n}</span></div>
        <div class="info-item"><b>Comments</b><span>${b}</span></div>
        <div class="info-item"><b>Downloads</b><span>${w}</span></div>
      </div>
    </li>`).join("");f.insertAdjacentHTML("beforeend",r),B.refresh()}function M(){f.innerHTML=""}function p(){m.classList.remove("hidden")}function g(){m.classList.add("hidden")}function L(){y.classList.remove("hidden")}function c(){y.classList.add("hidden")}let l="",i=1;const v=15,O=document.querySelector(".form"),x=document.querySelector(".load-more");O.addEventListener("submit",async t=>{t.preventDefault();const r=t.currentTarget.elements["search-text"].value.trim();if(r!==""){l=r,i=1,M(),c(),p();try{const s=await u(l,i);if(s.hits.length===0){d.error({message:"No images found!"});return}h(s.hits),s.totalHits>v&&L()}catch(s){console.error(s)}finally{g()}}});x.addEventListener("click",async()=>{i+=1,c(),p();try{const t=await u(l,i);h(t.hits),E();const r=Math.ceil(t.totalHits/v);i>=r?(c(),d.info({message:"We're sorry, but you've reached the end of search results."})):L()}catch(t){console.error(t)}finally{g()}});function E(){const t=document.querySelector(".gallery-item");if(t){const r=t.getBoundingClientRect().height;window.scrollBy({top:r*2})}}
//# sourceMappingURL=index.js.map
