import{a as S,S as P,i as c}from"./assets/vendor-CQi4fInE.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const $="55080821-ae3987ed548899e0d87a95a06",q="https://pixabay.com/api/";async function u(t,r){const a=new URLSearchParams({key:$,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:15});return(await S.get(`${q}?${a}`)).data}const m=document.querySelector(".gallery"),f=document.querySelector(".loader"),y=document.querySelector(".load-more"),B=new P(".gallery a",{captionsData:"alt",captionDelay:250});function g(t){const r=t.map(({webformatURL:a,largeImageURL:s,tags:e,likes:o,views:n,comments:b,downloads:w})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${s}">
        <img class="gallery-image" src="${a}" alt="${e}" />
      </a>
      <div class="info">
        <div class="info-item"><b>Likes</b><span>${o}</span></div>
        <div class="info-item"><b>Views</b><span>${n}</span></div>
        <div class="info-item"><b>Comments</b><span>${b}</span></div>
        <div class="info-item"><b>Downloads</b><span>${w}</span></div>
      </div>
    </li>`).join("");m.insertAdjacentHTML("beforeend",r),B.refresh()}function M(){m.innerHTML=""}function h(){f.classList.remove("hidden")}function p(){f.classList.add("hidden")}function L(){y.classList.remove("hidden")}function l(){y.classList.add("hidden")}let d="",i=1;const v=15,O=document.querySelector(".form"),x=document.querySelector(".load-more");O.addEventListener("submit",async t=>{t.preventDefault();const r=t.currentTarget.elements["search-text"].value.trim();if(r!==""){d=r,i=1,M(),l(),h();try{const a=await u(d,i);if(a.hits.length===0){c.error({message:"No images found!"});return}g(a.hits),a.totalHits>v&&L()}catch(a){console.error(a),c.error({message:"Something went wrong. Please try again later."})}finally{p()}}});x.addEventListener("click",async()=>{i+=1,l(),h();try{const t=await u(d,i);g(t.hits),E();const r=Math.ceil(t.totalHits/v);i>=r?(l(),c.info({message:"We're sorry, but you've reached the end of search results."})):L()}catch(t){console.error(t),c.error({message:"Failed to load more images."})}finally{p()}});function E(){const t=document.querySelector(".gallery-item");if(t){const r=t.getBoundingClientRect().height;window.scrollBy({top:r*2})}}
//# sourceMappingURL=index.js.map
