import{a as m,S as f,i}from"./assets/vendor-DQvd0HNi.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const p="55080821-ae3987ed548899e0d87a95a06",y="https://pixabay.com/api/";async function g(a,r){const o=new URLSearchParams({key:p,q:a,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:15});return(await m.get(`${y}?${o}`)).data}const c=document.querySelector(".gallery"),l=document.querySelector(".loader"),h=document.querySelector(".load-more"),L=new f(".gallery a",{captionsData:"alt",captionDelay:250});function v(a){const r=a.map(({webformatURL:o,largeImageURL:s,tags:e,likes:t,views:n,comments:d,downloads:u})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${s}">
        <img class="gallery-image" src="${o}" alt="${e}" />
      </a>
      <div class="info">
        <div class="info-item"><b>Likes</b><span>${t}</span></div>
        <div class="info-item"><b>Views</b><span>${n}</span></div>
        <div class="info-item"><b>Comments</b><span>${d}</span></div>
        <div class="info-item"><b>Downloads</b><span>${u}</span></div>
      </div>
    </li>`).join("");c.innerHTML=r,L.refresh()}function b(){c.innerHTML=""}function S(){l.classList.remove("hidden")}function w(){l.classList.add("hidden")}function q(){h.classList.remove("hidden")}const P=document.querySelector(".form"),$=document.querySelector(".load-more");P.addEventListener("submit",M);async function M(a){a.preventDefault();const r=a.currentTarget.elements["search-text"].value.trim();if(r===""){i.warning({message:"Please enter a search query!",position:"topRight"});return}b(),S();try{const o=await g(r);if(o.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}v(o.hits),q()}catch(o){console.error(o),i.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{w(),a.target.reset()}}$.addEventListener("click",O);async function O(a){}
//# sourceMappingURL=index.js.map
